name: deploy

on:
  push:
    paths-ignore:
    - '.github/**'
    - 'infrastructure/**'
    branches:
    - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Copy deployment script to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.EC2_AUTH }}
          source: "deploy.sh"
          target: "/tmp/"

      - name: Deploy reverse proxy icap
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_AUTH }}
          port: ${{ secrets.PORT }}
          script: |
            chmod +x /tmp/deploy.sh
            /tmp/deploy.sh
